### ISSUE TITLE
About code wrt to the latest version of your paper

### ISSUE THREAD

**Issue by huanli2012** [jramapuram/LifelongVAE#2]
I am studying lifelong learning and I have read your great paper _Lifelong Generative Model_.  You have updated your paper to [v6](https://arxiv.org/abs/1705.09847v6). This tf code is inconsistent with your latest version of the paper, neither the [torch code](https://github.com/jramapuram/LifelongVAE_pytorch). Could you release source code corresponding to the latest version please? Thank you.

**Comment by jramapuram** [comment]
Hi there,

Thanks for the interest! Yes the tf code is depreciated.

I am working on cleaning up the code to the final version in the following
branch:
https://github.com/jramapuram/LifelongVAE_pytorch/tree/feature/distributed_impl?files=1
however I will not be able to push the most recent changes for a few weeks.
Please bear with me!

**Comment by huanli2012** [comment]
Thank you for opening source code. I will follow with interest and looking forward to your early release.
